# permissions for end users to view postgressqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgressql-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-operator
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgressql-viewer-role
rules:
- apiGroups:
  - database.vygos.io
  resources:
  - postgressqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.vygos.io
  resources:
  - postgressqls/status
  verbs:
  - get
