---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - database.vygos.io
  resources:
  - postgressqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.vygos.io
  resources:
  - postgressqls/finalizers
  verbs:
  - update
- apiGroups:
  - database.vygos.io
  resources:
  - postgressqls/status
  verbs:
  - get
  - patch
  - update
